### ISSUE TITLE
v3.7 ReactNative 初始化模版失败

### ISSUE THREAD

**Issue by isnolan** [NervJS/taro-project-templates#110]
```
  taro taro init --template-source github:NervJS/taro-project-templates#v3.7
👽 Taro v3.6.15

⚠ 获取 taro 全局配置文件失败，不存在全局配置文件：/Users/yhostc/.taro-global-config/index.json


Taro 即将创建一个新项目!
Need help? Go and open issue: https://tls.jd.com/taro-issue-helper

? 请输入项目名称！ ChatOnce
? 请输入项目介绍 ChatOnce, Write Freely, Speak Confidently.
? 请选择框架 React
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择编译工具 Webpack5
? 请选择包管理工具 yarn
✔ 拉取远程模板仓库成功！
? 请选择模板 react-native
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.join (node:path:1176:7)
    at Object./src/pages/index/index.config.js (/Users/yhostc/.nvm/versions/node/v19.4.0/lib/node_modules/@tarojs/cli/templates/react-native/template_creator.js:37:25)
    at /Users/yhostc/.nvm/versions/node/v19.4.0/lib/node_modules/@tarojs/cli/src/create/init.ts:77:43
    at Generator.next (<anonymous>)
    at /Users/yhostc/.nvm/versions/node/v19.4.0/lib/node_modules/@tarojs/cli/dist/create/init.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/yhostc/.nvm/versions/node/v19.4.0/lib/node_modules/@tarojs/cli/dist/create/init.js:4:12)
    at /Users/yhostc/.nvm/versions/node/v19.4.0/lib/node_modules/@tarojs/cli/src/create/init.ts:60:30 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v19.4.0
```

**Comment by zhoujugui-web** [comment]
请问找到解决办法了吗？

**Comment by zhiqingchen** [comment]
3.7 还未正式发布
3.6 的 taro 需要使用 3.6 的模板
