### ISSUE TITLE
4.0.4版本  RN build失败

### ISSUE THREAD

**Issue by aispringli** [NervJS/taro-project-templates#133]
`
Failed to construct transformer:  TypeError: Transformer is not a constructor
    at getTransformCacheKey (W:\codes\gitlab\app\RnApp\node_modules\metro\src\DeltaBundler\Transformer\getTransformCacheKey.js:33:31)
    at new Transformer (W:\codes\gitlab\app\RnApp\node_modules\metro\src\DeltaBundler\Transformer.js:147:28)
    at W:\codes\gitlab\app\RnApp\node_modules\metro\src\Bundler.js:54:29
error Cannot read properties of undefined (reading 'transformFile'). Run CLI with --verbose flag for more details.
TypeError: Cannot read properties of undefined (reading 'transformFile')
    at W:\codes\gitlab\app\RnApp\node_modules\metro\src\Bundler.js:91:34
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (W:\codes\gitlab\app\RnApp\node_modules\metro\src\Bundler.js:14:24)
    at _next (W:\codes\gitlab\app\RnApp\node_modules\metro\src\Bundler.js:34:9)
`

**Comment by Engimaz** [comment]
发一下你的package.json。我最近也遇到过。注意metro版本与之对应即可解决
