### ISSUE TITLE
package.json模板文件有问题

### ISSUE THREAD

**Issue by GavintheAmateur** [NervJS/taro-project-templates#7]
请输入项目介绍！
? 是否需要使用 TypeScript ？ No
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择模板 默认模板
SyntaxError: Error parsing /Users/***/.nvm/versions/node/v13.6.0/lib/node_modules/@tarojs/cli/templates/default/package.json: Unexpected token < in JSON at position 183
    at parse (<anonymous>)
    at readPackage (internal/modules/cjs/loader.js:255:20)
    at readPackageScope (internal/modules/cjs/loader.js:280:19)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:17)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/***/.nvm/versions/node/v13.6.0/lib/node_modules/@tarojs/cli/dist/create/init.js:147:54)
    at Generator.next (<anonymous>) {
  path: '/Users/***/.nvm/versions/node/v13.6.0/lib/node_modules/@tarojs/cli/templates/default/package.json'
}

**Comment by GavintheAmateur** [comment]
使用node10版本可用
